version: '3.3'
services:
  consolidated-server-data:
    container_name: cs-postgres
    image: postgres:12-alpine
    restart: always
    env_file:
    - ./dev/database/postgres/database.env # configure postgres
    ports:
    - 55432:5432
    volumes:
    - /var/lib/consolidated-server/postgresdata:/var/lib/postgresql/data
    - ./dev/database/postgres/init/:/docker-entrypoint-initdb.d/
    networks:
    - backend-network

  fhir-hose.openelis.org:
    container_name: cs-fhir-hose
    image: fhir-hose
    build:
      context: ./bulk-data-requester/
      dockerfile: docker/docker-build/Dockerfile
    restart: always
    volumes:
      - ./dev/ssl/cs.keystore:/usr/local/tomcat/certs/keystore
      - ./dev/ssl/cs.truststore:/usr/local/tomcat/certs/truststore
    networks:
      - backend-network

  hapi-fhir-jpaserver:
    container_name: cs-hapi-fhir-jpaserver
    image: hapiproject/hapi:v5.4.1
    restart: always
    ports:
    - 58444:8443
    volumes:
    - ./dev/properties/application.yaml:/data/hapi/application.yaml
    - ./dev/tomcat/hapi_server.xml:/usr/local/tomcat/conf/server.xml
    - ./dev/ssl/cs.keystore:/usr/local/tomcat/certs/keystore
    - ./dev/ssl/cs.truststore:/usr/local/tomcat/certs/truststore
    environment: 
      SPRING_CONFIG_LOCATION: file:///data/hapi/application.yaml
    networks:
    - backend-network
    
  mongo:
    container_name: openhim-mongo
    restart: always
    ports:
    - 27017:27017
    image: mongo:3.4 
    environment:
    - MONGO_INITDB_ROOT_USERNAME_FILE=/var/lib/openhim/mongo_root_user
    - MONGO_INITDB_ROOT_PASSWORD_FILE=/var/lib/openhim/mongo_root_password
    - MONGO_INITDB_USERNAME_FILE=/var/lib/openhim/mongo_user
    - MONGO_INITDB_PASSWORD_FILE=/var/lib/openhim/mongo_password
    volumes:
     - /var/lib/consolidated-server/mongodata:/data/db
     - ./dev/database/mongo/init/:/docker-entrypoint-initdb.d/
     - ./dev/database/mongo/db_root_user:/var/lib/openhim/mongo_root_user
     - ./dev/database/mongo/db_root_password:/var/lib/openhim/mongo_root_password
     - ./dev/database/mongo/db_user:/var/lib/openhim/mongo_user
     - ./dev/database/mongo/db_password:/var/lib/openhim/mongo_password
    networks:
    - backend-network
    
  openhim-core:
    container_name: openhim-core
    restart: always
    image: jembi/openhim-core:7.0.2
    env_file:
    - dev/properties/openhim.env
    ports:
    - 58080:8080
    - 55000:5000
    - 55001:5001
    - 55050:5050
    - 55051:5051
    - 55052:5052
    - 57788:7788
    depends_on:
    - mongo
    volumes:
    - ./dev/properties/openhim-core_default.json:/usr/src/app/config/default.json
    networks:
    - frontend-network
    - backend-network
    
  #accessed through nginx container
  openhim-console:
    container_name: openhim-console
    restart: always
    image: jembi/openhim-console:1.10.0
    volumes:
    - ./dev/conf/nginx_openhim-console.conf:/etc/nginx/conf.d/default.conf
    - ./dev/ssl/cs.crt:/etc/nginx/serverCerts/cs.crt
    - ./dev/ssl/cs.key:/etc/nginx/serverCerts/cs.key
    - ./dev/ssl/key_pass:/etc/nginx/private/key_pass
    - ./dev/properties/openhim-console_default.json:/usr/share/nginx/html/config/default.json
    networks:
    - frontend-network
    - backend-network
    
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    restart: always
    ports:
    - 50080:80
    - 50443:443
    volumes:
    - ./dev/conf/nginx_main.conf:/etc/nginx/conf.d/default.conf
    - ./dev/ssl/cs_frontend.crt:/etc/nginx/serverCerts/cs.crt
    - ./dev/ssl/cs_frontend.key:/etc/nginx/serverCerts/cs.key
    - ./dev/ssl/key_pass_frontend:/etc/nginx/private/key_pass
    networks:
    - frontend-network
    
networks:
  frontend-network: 
  backend-network: 
