version: '3.3'
services:

   #this is here since we can't just pull a built image from the cloud with our libraries
  itech-fhir-libraries:
   image: itech-fhir-libraries
   build:
      context: .

      dockerfile: docker/docker-build/Dockerfile
      
  cs-frontend:
    image: cs-frontend
    build:
      context: ./cs-frontend
      dockerfile: ./Dockerfile    
    depends_on:
      - dataimport.openelis.org
    ports:
      - 3000:3000
    networks:
      - frontend
      - server-1  
    volumes:
      - './cs-frontend:/app'
      - '/app/node_modules'
    secrets:
      - source: cert
      - source: key
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    
  consolidated-server-data:
    image: postgres:12-alpine
    env_file:
      - ./dev/database/database.env # configure postgres
    ports:
      - 25432:5432
    volumes:
      - consolidated-server-data:/var/lib/postgresql/data
      - ./dev/database/dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql
    networks:
      - server-1
    
  dataimport.openelis.org:
    image: dataimport-webapp
    build:
      context: ./dataimport-webapp
      dockerfile: docker/docker-build/Dockerfile
    depends_on:
      - consolidated-server-data
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - server-1
    volumes:
      - ./dev/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    extra_hosts:
#    this should be the loopback to the docker host. 
#    run 
#    /sbin/ip route|awk '/default/ { print $3 }' 
#    inside the container to make sure the ip address is correct
#    make sure connections to 8446 are allowed by your firewall
      - host.openelis.org:172.20.0.1
    secrets:
      - source: keystore
      - source: truststore
      
  fhir.openelis.org:
    build: ./hapi-fhir-jpaserver-starter
    restart: always
    environment:
      - JAVA_OPTS= -Dhapi.properties=/run/secrets/hapi.properties
    ports:
      - 8444:8443
    networks:
      - frontend
      - server-1  
    volumes:
      - ./dev/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    secrets:
      - source: hapi.properties
      - source: keystore
      - source: truststore

  auth.openelis.org:
    image:
      quay.io/keycloak/keycloak:10.0.2
    restart: always
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=consolidated-server-data
      - DB_PORT=5432
      - DB_DATABASE=consolidated-server
      - DB_SCHEMA=keycloak
      - DB_USER=cs_user
      - DB_PASSWORD=cs_password
    ports:
      - 8083:8080
      - 8446:8443
    networks:
      - frontend
      - server-1
    volumes:
      - ./dev/ssl/oe_selfsigned.crt:/etc/x509/https/tls.crt
      - ./dev/ssl/oe_selfsigned.key:/etc/x509/https/tls.key

networks:
  frontend:
  server-1:
  
volumes:
  consolidated-server-data:
  
secrets:
  hapi.properties:
    file: ./dev/properties/hapi.properties
  keystore:
    file: ./dev/ssl/oe_selfsigned.keystore
  truststore:
    file: ./dev/ssl/oe_selfsigned.truststore
  cert:
    file: ./dev/ssl/oe_selfsigned.crt
  key:
    file: ./dev/ssl/oe_selfsigned.key

