version: '3'

services:
#this is here since we can't just pull a built image from the cloud with our libraries
  itech-fhir-libraries:
   image: itech-fhir-libraries
   build:
      context: .
      dockerfile: docker/docker-build/Dockerfile
      
  cs-frontend:
    image: cs-frontend
    build:
      context: ./cs-frontend
      dockerfile: ./Dockerfile    
    depends_on:
      - datasubscriber-webapp
      - dataimport-webapp
    ports:
      - 3000:3000
    networks:
      - frontend
      - server-1  
    volumes:
      - './cs-frontend:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    
  dataimport-webapp:
    image: dataimport-webapp
    build:
      context: ./dataimport-webapp
      dockerfile: docker/docker-build/Dockerfile
    depends_on:
      - consolidated-server-data
    ports:
      - 8083:8080
    links:
      - "consolidated-server-data:dataimport-webapp-database"
      - "hapi-fhir-jpaserver-start-1:hapi-fhir-jpaserver-start"
    networks:
      - frontend
      - server-1
  consolidated-server-data:
    image: postgres:12-alpine
    env_file:
      - ./docker/database.env # configure postgres
    ports:
      - 5436:5432
    volumes:
      - consolidated-server-data:/var/lib/postgresql/data
    networks:
      - frontend
      - server-1
  hapi-fhir-jpaserver-start-1:
    build: ./hapi-fhir-jpaserver-starter
    ports:
      - "8080:8080"
    links:
      - "hapi-fhir-mysql-1:hapi-fhir-mysql"
    networks:
      - server-1
  hapi-fhir-mysql-1:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - server-1
    volumes:
      - hapi-fhir-mysql-1:/var/lib/mysql

  hapi-fhir-jpaserver-start-2:
    build: ./hapi-fhir-jpaserver-starter
    ports:
      - "8081:8080"
    links:
      - "hapi-fhir-mysql-2:hapi-fhir-mysql"
    networks:
      - frontend
      - server-2
  hapi-fhir-mysql-2:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - server-2
    volumes:
      - hapi-fhir-mysql-2:/var/lib/mysql
      
networks:
  frontend:
  server-1:
  server-2:
      
volumes:
  consolidated-server-data:
  hapi-fhir-mysql-2:
  hapi-fhir-mysql-1:
